[package]
name = "hktb"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
hex = "0.4.3"
html-escape = "0.2.13"
log = "0.4.29"
simplelog = "0.12.2"
thiserror = "2.0.17"
urlencoding = "2.1.3"
